[service]
name = "mcpov3"

[build]
builder = "dockerfile"

[dockerfile]
path = "./Dockerfile"

[ports]
http = 8000

[deploy]
startCommand = "/bin/sh -c '
mkdir -p /app/config
cat <<EOF > /app/config/config.json
{
  \"mcpServers\": {
    \"starter\": {
      \"type\": \"streamable_http\",
      \"url\": \"https://${N8N_PUBLIC_DOMAIN}/mcp/starter\"
    },
    \"page_request\": {
      \"type\": \"streamable_http\",
      \"url\": \"https://${N8N_PUBLIC_DOMAIN}/mcp/page-request\"
    }
  }
}
EOF

exec uvx mcpo --port 8000 --name n8n_tool --config /app/config/config.json --hot-reload 
'"

[[envVars]]
key = "MCPO_API_KEY"
value = "your-secret-key"

[[envVars]]
key = "SERVER_TYPE"
value = "streamable-http"
